### PR TITLE
Update analysis.R: netAnalysis_contribution

### PR DESCRIPTION
**Pull request by GildasLepennetier**
added order releveling for ggplot2

### CODE REVIEW

**Review by sqjin — CHANGES_REQUESTED** [review]
Thanks for your contribution! However, I think there are still potential issue for your edit.  Please test the following changes and update the pull quest if it works. 
`    df$name <- factor(df$name,levels=df$name[order(df$contribution, decreasing = TRUE)])
    
df1$name <- factor(df1$name,levels=df1$name[order(df1$contribution, decreasing = TRUE)])`

**Comment by GildasLepennetier** [comment]
I actually did not see the multiple call to ggplot (4 times). The df1 is never used in the ggplot, and the df is re-created several time, I actually added this ordering before each ggplot call.

**Comment by sqjin** [comment]
You will get a complete wrong result if you do not re-order df1, which is used when re-labeling the axis text

**Comment by sqjin** [comment]
I have simply updated the codes in Github. Thanks!

**Pull request closed without merging**
